### ISSUE TITLE
[Feature Request] Python Parser Library please?

### ISSUE THREAD

**Issue by northdpole** [iriusrisk/OpenThreatModel#2]
Hi, this seems like a good idea, do you have any plans on releasing parsers libraries for popular languages?
Then we could make popular threat modeling tools talk to each other.

**Comment by dfernandezvigo** [comment]
Hey northdpole,
thanks for your interest in Open Threat Model (OTM)!
Yes, an OTM parser exists on github called startleft, available on [https://github.com/iriusrisk/startleft](https://github.com/iriusrisk/startleft). This Python program allows to interact with OTM by parsing various input formats such as CloudFormation, Terraform and Visio to OTM format. It can be run as a standalone file format conversion or be run as a REST service.
We are evaluating the best way to evolve this software.
Hope this helps!
Cheers
The IriusRisk developers team

**Comment by daFont-iriusrisk** [comment]
As @dfernandezvigo provide info about our Python parser and there is no response from @northdpole  since September I'll close this issue.

Thank you @northdpole for sharing your thoughts with us.
