### ISSUE TITLE
Strict compiling of schema produces warnings

### ISSUE THREAD

**Issue by jgadsden** [iriusrisk/OpenThreatModel#23]
When compiling the OTM schema using [ajv version 8.11.0](https://www.npmjs.com/package/ajv) in strict mode (which is the default) we get the following warnings 

* strict mode: missing type "object" for keyword "required" at "https://iriusrisk.com/schema/otm-0.2.0.schema.json#/properties/representations" (strictTypes)
* strict mode: missing type "object" for keyword "properties" at "https://iriusrisk.com/schema/otm-0.2.0.schema.json#/properties/representations" (strictTypes)
* strict mode: missing type "object" for keyword "required" at "https://iriusrisk.com/schema/otm-0.2.0.schema.json#/properties/assets" (strictTypes)
* strict mode: missing type "object" for keyword "properties" at "https://iriusrisk.com/schema/otm-0.2.0.schema.json#/properties/assets" (strictTypes)

**Comment by jgadsden** [comment]
The reason for the warnings is because 'representations' and 'assets' are defined as arrays but not as arrays of objects

**Comment by dantolin-iriusrisk** [comment]
Hi, @jgadsden! Thank you for the warning. We'll do the change to keep it clean.

**Comment by jgadsden** [comment]
OK, do you want me to contribute? Or I can leave it with you

**Comment by dantolin-iriusrisk** [comment]
As you have the change well identified, feel free to contribute, of course!
