### ISSUE TITLE
[Suggestion] rename/redefine AssetRisk object

### ISSUE THREAD

**Issue by fixbits** [iriusrisk/OpenThreatModel#8]
Dear Team, 

Based on the description of the object the semantics behind AssetRisk is not clear:

"This object describes the different ways in which a compromise of this asset can be harmful. ...

    risk:
      confidentiality: 100
      integrity: 100
      availability: 100
      riskComments: We have decided that the values are a 100 for all values since this highly sensitive information"
      
Specifically:
- it is not clear, how AssetRisk relates to a threat
     - does it influence impact?
     - does it influence likelihood?
     - non of the above / purely subject to interpretation as the service parsing the OTM file sees fit?

Could you maybe add an example what could be a practical implication of an AssetRisk.confidentiality being 0 or 50 instead of 100?

**Comment by Jayarr03** [comment]
AssetRisk influences impact with regard to a threat. 

Those values are passed through OTM into the IR rules engine which performs the calculation for inherent risk. 

More information - (https://support.iriusrisk.com/hc/en-us/articles/4412644787345-How-is-inherent-risk-calculated-)

**Comment by fixbits** [comment]
Thanks!

would you mind adding this one liner description to the OTM? It would clarify a lot.

**Comment by Jayarr03** [comment]
Let me reach out to that team and see if they can get that added.
________________________________
